"""add_s3_connections

Revision ID: 347f598ea82e
Revises: 
Create Date: 2025-12-05 00:08:01.815788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347f598ea82e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('auth_method', sa.Enum('ACCESS_KEY', 'IAM_ROLE', 'IAM_ROLES_ANYWHERE', name='authmethod'), nullable=False),
    sa.Column('access_key_id', sa.String(), nullable=True),
    sa.Column('secret_access_key', sa.String(), nullable=True),
    sa.Column('role_arn', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s3_connections_id'), 's3_connections', ['id'], unique=False)
    op.create_index(op.f('ix_s3_connections_name'), 's3_connections', ['name'], unique=True)
    op.add_column('permissions', sa.Column('s3_connection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'permissions', 's3_connections', ['s3_connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 's3_connection_id')
    op.drop_index(op.f('ix_s3_connections_name'), table_name='s3_connections')
    op.drop_index(op.f('ix_s3_connections_id'), table_name='s3_connections')
    op.drop_table('s3_connections')
    # ### end Alembic commands ###
